### ISSUE TITLE
Allow click version to float

### ISSUE THREAD

**Issue by jonathansick** [lsst-sqre/templatekit#11]
ERROR: cookiecutter 1.7.0 has requirement click>=7.0, but you'll have click 6.7 which is incompatible.

**Comment by jonathansick** [comment]
I've confirmed that cookiecutter 1.70 doesn't work with click 6.7:

```
  File "site-packages/cookiecutter/prompt.py", line 187, in prompt_choice_for_config
    return read_user_choice(key, rendered_options)
  File "site-packages/cookiecutter/prompt.py", line 85, in read_user_choice
    prompt, type=click.Choice(choices), default=default, show_choices=False
TypeError: prompt() got an unexpected keyword argument 'show_choices'
```

**Comment by normansaez** [comment]
I got the same issue:

    prompt, type=click.Choice(choices), default=default, show_choices=False
TypeError: prompt() got an unexpected keyword argument 'show_choices'

**Comment by rra** [comment]
Fixed in 0.4.1 via 16754f2d0efaf2a1630e7e9f7c1aaeb927b9c466
